[plugin]
repository = "https://github.com/Lynesth/BetterTargetingSystem.git"
commit = "86c98bf52abd6fe7fdf1cc9dbbdc31872b5f7ec7"
owners = ["Lynesth"]
project_path = "BetterTargetingSystem"
changelog = "Initial submission"
