[plugin]
repository = "https://github.com/Lynesth/BetterTargetingSystem.git"
commit = "27ffb252fd187200c9220c188611269e773b846d"
owners = ["Lynesth"]
project_path = "BetterTargetingSystem"
changelog = "Initial submission"
