[plugin]
repository = "https://github.com/Lynesth/BetterTargetingSystem.git"
commit = "27eaac89b0ca1198565ceed8c5d0f3d7c8e46476"
owners = ["Lynesth"]
project_path = "BetterTargetingSystem"
changelog = "Initial submission"
