[plugin]
repository = "https://github.com/Lynesth/BetterTargetingSystem.git"
commit = "fc570e8affc5dd7f5b570ea1f1b87a949caa25c7"
owners = ["Lynesth"]
project_path = "BetterTargetingSystem"
changelog = "Initial submission"
