[plugin]
repository = "https://github.com/Lynesth/BetterTargetingSystem.git"
commit = "4459d1db1bfa8d445cc1e52be95b47695abc9a8f"
owners = ["Lynesth"]
project_path = "BetterTargetingSystem"
changelog = "Initial submission"
