[plugin]
repository = "https://github.com/Lynesth/BetterTargetingSystem.git"
commit = "c49711475cb98a72b0fe7d344323fcc5f1708276"
owners = ["Lynesth"]
project_path = "BetterTargetingSystem"
changelog = "Initial submission"
